name: Moderator
version: 1.0.1
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.1]
author: Driesboy & Zeao
main: Driesboy\Main
description: A Moderation plugin for VoidMinerPE.
commands:
  warn:
    permission: rank.moderator
    description: Warn a player that is breaking the rules!
  staffinfo:
    permission: rank.moderator
    description: Info page for our staffs!
  forceban:
    permission: rank.srmoderator
    description: Ban a player that is breaking the rules!
  report:
    description: Report a player that is breaking the rules!
permissions:
  rank.moderator:
    default: op
  rank.srmoderator:
    default: op
